### ISSUE TITLE
how did you realize the adversarial process in your code?

### ISSUE THREAD

**Issue by maliho0803** [chenbinghui1/MHN#1]
hi, in you paper, in order to suppress  the problem of order collapse, you introduce the adversarial loss. however, I did not find adversarial process, you just minimize the loss_div?

if I loss some information about your code?

**Comment by chenbinghui1** [comment]
@maliho0803  Hi, as in paper, the adv loss is minimized for adv net, and maximized for HOA, thus we use a gradients reverse layer to implement the maximizing process. And the code is in Line82 of losses.py
