### ISSUE TITLE
如何测试

### ISSUE THREAD

**Issue by Be-yourself-zxy** [chenbinghui1/MHN#11]
作者您好：
      我在按照readme 上面的介绍训练完之后进行评估，但是得不出结果，而是出现如下情况
lei@lei:/data/zxy/MHN-master$ python3 test_smallPCB.py --gpu_ids 0,1 --name pcb_mhn6 --test_dir /data/zxy/MHN-master/datasets/Market/datasets/pytorch/ --batchsize 10 --which_epoch 69 --mhn --parts 6
-------test-----------
在执行了python3 evaluate_gpu.py 之后会得出结果，但是并不知道具体是哪个方法的结果，期待您的解答，谢谢！

**Comment by chenbinghui1** [comment]
@Be-yourself-zxy 测试只支持了单卡的，你试试单卡测一下

**Comment by Be-yourself-zxy** [comment]
lei@lei:/data/zxy/MHN-master$ python3 test_smallPCB.py --gpu_ids 0 --name pcb_mhn6 --test_dir /data/zxy/MHN-master/datasets/Market/datasets/pytorch/ --batchsize 10 --which_epoch 69 --mhn --parts 6
-------test-----------
lei@lei:/data/zxy/MHN-master$ python3 test_smallPCB.py --gpu_ids 1 --name pcb_mhn6 --test_dir /data/zxy/MHN-master/datasets/Market/datasets/pytorch/ --batchsize 10 --which_epoch 69 --mhn --parts 6
-------test-----------
尝试了单卡依然不行

**Comment by chenbinghui1** [comment]
@Be-yourself-zxy 建议你单步调试一下，或者打印一下节点，看看哪里出问题了

**Comment by chenbinghui1** [comment]
@Be-yourself-zxy 或者多等等，测试是比较慢的 毕竟batchsize只有10
