### ISSUE TITLE
Cuhk03 dataset

### ISSUE THREAD

**Issue by InstantWindy** [chenbinghui1/MHN#12]
Hi.The CUHK dataset has 6 cameras, but the dataset in the download link you provided has only 2 cameras.

**Comment by chenbinghui1** [comment]
@InstantWindy  Hi, friend, thanks for your interest first.
We provided CUHK-NP dataset not CUHK dataset. CUHK-NP dataset indeed has 2 cameras. Please see https://github.com/zhunzhong07/person-re-ranking/blob/master/CUHK03-NP/README.md
