### ISSUE TITLE
he correct rate of the model obtained is very low

### ISSUE THREAD

**Issue by GJTNB** [chenbinghui1/MHN#13]
Hello, due to the poor configuration of my equipment, I modified the batchsize during training and changed it to 10, so the correct rate of the model obtained is very low. May I ask if it is due to my modification of the batchsize.

**Comment by chenbinghui1** [comment]
This might be a reason. If you just have poor equipment, you should not care about the absolute performance values. You can check whether the improvements can be achieved over the baseline(Note that the baseline should also be performed under the same training configurations).

**Comment by GJTNB** [comment]
thanks
