### ISSUE TITLE
利用MHN模型训练，应该运行哪一个文件？

### ISSUE THREAD

**Issue by xyc-henu** [chenbinghui1/MHN#14]
您好，我想问下要利用您的MHN模型训练，我应该运行哪一个文件？还有用rank跟map指标测试应该运行哪个文件？

**Comment by chenbinghui1** [comment]
@xyc-henu 请看readme里面的train_model部分 都很详细

**Comment by xyc-henu** [comment]
谢谢您，刚开始学习，有些部分没看明白。
