### ISSUE TITLE
Detail information about "fea" and "y"

### ISSUE THREAD

**Issue by liaojiacai** [chenbinghui1/MHN#7]
Dear author:
    Thanks for your great work, your paper and code are perfect. A good idea has been proposed in your paper, and clearly code realized it, what's more, your idea has a strong theoretical persuasion. While, when I print the output of the network, it was hard for me to understand the size of for an input image, parts=4, part = 3, the output size of "fea" are:
net output size"fea":
3x4x256
can I understand that for every input image, the networks will generate 12 features, and every feature's dimension is 256?

**Comment by chenbinghui1** [comment]
@liaojiacai Yes,you are right!
