### ISSUE TITLE
请问MHN在混合数据集上的性能？

### ISSUE THREAD

**Issue by CWF-999** [chenbinghui1/MHN#8]
我在混合数据集（将market,msmt17_2,cuhk03-np等七八个数据集统一成一个格式）训练ide和ide_mhn网络，发现不管阶数多少，是否使用随机擦除等技巧，最后的性能测试mhn网络rank1,5,10,mAp都会下降1-2个点，这个注意力在跨数据集不管用了吗？还是啥其他原因？

**Comment by whut2962575697** [comment]
你好，我在训练的时候发现adv loss不收敛，总的loss也很难收敛，请问你遇到过这样的问题吗，我的图像大小使用的是256*128

**Comment by CWF-999** [comment]
@whut2962575697 没有诶

**Comment by whut2962575697** [comment]
你是在原始代码上训练的吗

**Comment by CWF-999** [comment]
对的------------------ Original ------------------

**Comment by chenbinghui1** [comment]
@whut2962575697 直接按照默认参数训练就可以，advloss 肯定不会收敛到0，是对抗平稳的。

**Comment by chenbinghui1** [comment]
@wfchenwf 在混合域下，每个域的统计特性可能是不同的。需要特殊处理，这也是我们正在进行的后续工作
