### ISSUE TITLE
 adv loss difficult to convergence

### ISSUE THREAD

**Issue by whut2962575697** [chenbinghui1/MHN#9]
Thank you for your great work, but when I tried to train the network, I found that adv loss is difficult to converge. Is it because the network is sensitive to certain parameters? The image size I used when training was 256 * 128.Does this affect convergence of adv loss?

**Comment by chenbinghui1** [comment]
@whut2962575697 the adv loss actually cannot converge to zero, due to the nash equilibrium. if if converge too fast towards zero, it might not perform better.
